[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "suntime"
dynamic = ["version"]
description = "Simple sunset and sunrise time calculation python library"
readme = "README.md"
license = { text = "LGPLv3" }
authors = [
  { name = "Andrey Kobyshev" },
  { name = "Hadrien Bertrand" },
  { name = "Ingo Randolf" },
  { name = "Jakob R.F." },
  { name = "John Vandenbergg" },
  { name = "Krzysztof Stopa" },
  { name = "Matthias" },
  { name = "Muhammad Yasirroni" },
  { name = "M. Amrehn" },
  { name = "Sijmen Huizenga" },
]
dependencies = ["python-dateutil>=2.1.0"]

[project.optional-dependencies]
dev = ["pytest", "ruff"]

[project.urls]
Homepage = "https://github.com/SatAgro/suntime"

[tool.setuptools.dynamic]
version = { attr = "suntime.__version__" }

[tool.setuptools]
packages = ["suntime"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "W"]

[tool.ruff.lint.per-file-ignores]
"suntime/__init__.py" = ["F401"]
